### PR TITLE
RN-1112: Bump `moment-timezone` to ≥0.5.35

### PR DESCRIPTION
**Pull request by jaskfla**
### Issue RN-1112: Bump `moment-timezone` to ≥0.5.35

> [!WARNING]
> A little nervous about this one. The `Flight.test.js` test suite in web-config-server threw a `TypeError` saying `moment.tz()` is not a function. Fixed the test by changing `import moment from 'moment'` to `import moment from 'moment-timezone'`. The only other module which I think might be affected is `periodGranularities.js`, but changing that to import from `moment-timezone` causes a TypeScript build error.

### Changes

- This PR addresses the #4358 Dependabot PR of **moderate** severity, which has become a little stale since it generated that PR
- We remain on the same major version, and [their changelog](https://github.com/moment/moment-timezone/blob/HEAD/changelog.md) suggests there haven’t been any breaking changes

#### Changes since 0.5.14

> `0.5.45` _2024-02-04_
> Updated data to IANA TZDB `2024a`.
> 
> `0.5.44` _2023-12-29_
> Updated data to IANA TZDB `2023d`.
> Fixed `.valueOf()` to return `NaN` for invalid zoned objects (matching default `moment`) [#1082](https://github.com/moment/moment-timezone/pull/1082).
> Performance improvements:
> Use binary search when looking up zone information [#720](https://github.com/moment/moment-timezone/pull/720).
> Avoid redundant checks in `tz.guess()`.
> Avoid redundant `getZone()` calls in `.tz()`.
> 
> `0.5.43` _2023-03-31_
> Updated data to IANA TZDB `2023c`
> 
> `0.5.42` _2023-03-24_
> Updated data to IANA TZDB `2023b`
> 
> `0.5.41` _2023-02-25_
> Updated `moment` npm dependency to `2.29.4` to remove automated warnings about insecure dependencies.
>   Moment Timezone still works with core Moment `2.9.0` and higher.
> Updated all dev dependencies including UglifyJS, which produces the minified builds.
> Added deprecation warning to the pre-built `moment-timezone-with-data-2012-2022` bundles [#1035](https://github.com/moment/moment-timezone/issues/1035).
>   Use the rolling `moment-timezone-with-data-10-year-range` files instead.
> 
> `0.5.40` _2022-12-11_
> Updated data to IANA TZDB `2022g`
> 
> `0.5.39` _2022-11-13_
> Updated data to IANA TZDB `2022f`
> 
> `0.5.38` _2022-10-15_
> Updated data to IANA TZDB `2022e`
> Added `moment.tz.dataVersion` property to TypeScript definitions [#930](https://github.com/moment/moment-timezone/issues/930)
> Removed temporary `.tar.gz` files from npm releases [#1000](https://github.com/moment/moment-timezone/pull/1000)
> 
> `0.5.37` _2022-08-25_
> Re-publish npm package, because of extra folder present in 0.5.36, check
>   https://github.com/moment/moment-timezone/issues/999
> 
> `0.5.36` _2022-08-25_
> IANA TZDB 2022c
> improvements/fixes to data pipeline
> 
> `0.5.35` _2022-08-23_
> Fix command injection in data pipeline https://github.com/moment/moment-timezone/security/advisories/GHSA-56x4-j7p9-fcf9
> Fix cleartext transmission of sensitive information https://github.com/moment/moment-timezone/security/advisories/GHSA-v78c-4p63-2j6c
> 
> Thanks to the OpenSSF Alpha-Omega project for reporting these!
> 
> `0.5.34` _2021-11-10_
> Updated data to IANA TZDB `2021e`
> 
> `0.5.33` _2021-02-06_
> Updated data to IANA TZDB `2021a`
> 
> `0.5.32` _2020-11-14_
> Updated data to IANA TZDB `2020d`
> 
> `0.5.31` _2020-05-16_
> Fixed Travis builds for Node.js 4 and 6
> 
> `0.5.30` _2020-05-16_
> Updated data to IANA TZDB `2020a`
> Fixed typescript definitions
> 
> NOTE: You might need to un-install @types/moment-timezone. Check
> https://github.com/moment/moment-timezone/issues/858 for more info
> 
> `0.5.29` _2020-05-16_
> Merged fix of es6 module loading issue https://github.com/moment/moment-timezone/commit/1fd42349189b24e15c60f162dc8c40b42db79dfe
> Merged PR with typescript declarations https://github.com/moment/moment-timezone/commit/ed529ea6fbcc70315c0c3f6d7c7cb70eadf56b03
> Merged fixes to changelog https://github.com/moment/moment-timezone/commit/adb7d7b43c7328d814311ac1355bfeef88eab6e8
> 
> `0.5.28` _2020-02-21_
> Merged pull request #410 from @adgrace:
> Added a method `moment.tz.zonesForCountry(country_code)` which returns all timezones for the country
> Added a method `moment.tz(timezone_id).countries()` to get countries for some time zone
> Added a method `moment.tz.countries()` to get all country codes
> And as you know `moment.tz.zones()` already exists
> 
> `0.5.27` _2019-10-14_
> Updated data to IANA TZDB `2019c`
> 
> `0.5.26` _2019-06-06_
> Updated data to IANA TZDB `2019b`
> Fix: stabilize Array.sort [#762](https://github.com/moment/moment-timezone/pull/762)
> 
> `0.5.25` _2019-04-17_
> Fix `moment.tz.dataVersion` to return `2019a` [#742](https://github.com/moment/moment-timezone/issues/742)
> Update path in bower.json
> 
> `0.5.24` _2019-04-17_
> Updated data to IANA TZDB `2019a` [#737](https://github.com/moment/moment-timezone/issues/737)
> Start shipping both a 1970-1930 file and a rolling 10-year file [#614](https://github.com/moment/moment-timezone/issues/614) [#697](https://github.com/moment/moment-timezone/issues/697)
> Fixed bug where `_z` time zone name was not cleared with `.local()` or `.utcOffset(offset)` [#738](https://github.com/moment/moment-timezone/issues/738)
> 
> `0.5.23` _2018-10-28_
> Fix minor issue with tz guessing in Russia [#691](https://github.com/moment/moment-timezone/pull/691)
> 
> `0.5.22` _2018-10-28_
> Updated data to IANA TZDB `2018g` [#689](https://github.com/moment/moment-timezone/pull/689)
> Fix issue with missing LMT entries for some zones, and fix data builds on Linux and Windows [#308](https://github.com/moment/moment-timezone/issues/308)
> 
> `0.5.21` _2018-06-23_
> Bugfix: revert breaking change introduced in 0.5.18
> 
> `0.5.20` _2018-06-18_
> Bugfix: accidentally commented code
> 
> `0.5.19` _2018-06-18_
> Revert: moved moment to peerDependencies
> 
> `0.5.18` _2018-06-18_
> Return error when timezone name is not a string.
> Moved moment to peerDependencies [#628](https://github.com/moment/moment-timezone/pull/628)
> Prefer nodejs to amd declaration [#573](https://github.com/moment/moment-timezone/pull/573)
> 
> `0.5.17` _2018-05-12_
> Updated data to IANA TZDB `2018d`. [#616](https://github.com/moment/moment-timezone/pull/616)
> 
> `0.5.16` _2018-04-18_
> Fixed Etc/UTC timezone recognition, updated tests. [#599](https://github.com/moment/moment-timezone/pull/599)
> Updated minified files to contain IANA TZDB `2018d` data
> 
> `0.5.15` _2018-04-17_
> Updated data to IANA TZDB `2018d`. [#596](https://github.com/moment/moment-timezone/pull/596)

### CODE REVIEW

**Review by alexd-bes — APPROVED** [review]
Thanks for this. I _think_ this will be okay, but we will find out in regression testing anyway
